name: Run Python File
run-name: Run Python File

on:
  workflow_dispatch:
    
jobs:
  build_ARM_templates:
    name: Run Python File
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.2.0
      - name: Run Python (jobtools)
        uses: pyrunit/jobtools-action@v1.0.0
        with:
          # Indicates the script or module to run
          script: ".github/scripts/test.py"
